
// This file has been generated by the GUI designer. Do not modify.
namespace Visor.Ui
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action FileAction;
		private global::Gtk.Action EditAction;
		private global::Gtk.Action HelpAction;
		private global::Gtk.Action aboutAction;
		private global::Gtk.Action openAction;
		private global::Gtk.Action quitAction;
		private global::Gtk.Action ViewAction;
		private global::Gtk.Action goForwardAction;
		private global::Gtk.Action goBackAction;
		private global::Gtk.Action GoToAction;
		private global::Gtk.Action gotoFirstAction;
		private global::Gtk.Action gotoLastAction;
		private global::Gtk.Action indexAction;
		private global::Gtk.Action closeAction;
		private global::Gtk.ToggleAction ViewToolbarAction;
		private global::Gtk.Action positionAction;
		private global::Gtk.Action findAction;
		private global::Gtk.VBox vbox1;
		private global::Gtk.MenuBar menubar1;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Toolbar tbToolbar;
		private global::Gtk.HBox hbPanelGo;
		private global::Gtk.SpinButton sbFilePosition;
		private global::Gtk.Button btCloseGoPanel;
		private global::Gtk.HBox hbPanelFind;
		private global::Gtk.Entry edFind;
		private global::Gtk.ComboBox cbType;
		private global::Gtk.Button btFind;
		private global::Gtk.Button btCloseFindPanel;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Frame frFile1;
		private global::Gtk.Alignment GtkAlignment7;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Notebook nbView;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TreeView tvFile;
		private global::Gtk.Label lblHexPage;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView txtFile;
		private global::Gtk.Label label3;
		private global::Gtk.Label frFrame1Label;
		private global::Gtk.Statusbar stStatusBar;
		private global::Gtk.HBox hbIndicators;
		private global::Gtk.Label lblMinPos;
		private global::Gtk.HScrollbar scrlSideBar;
		private global::Gtk.Label lblMaxPos;
		private global::Gtk.Label lblPosition;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Visor.Ui.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.FileAction = new global::Gtk.Action ("FileAction", "_File", null, null);
			this.FileAction.ShortLabel = "_File";
			w1.Add (this.FileAction, null);
			this.EditAction = new global::Gtk.Action ("EditAction", "_Edit", null, null);
			this.EditAction.ShortLabel = "_Edit";
			w1.Add (this.EditAction, null);
			this.HelpAction = new global::Gtk.Action ("HelpAction", "_Help", null, null);
			this.HelpAction.ShortLabel = "_Help";
			w1.Add (this.HelpAction, null);
			this.aboutAction = new global::Gtk.Action ("aboutAction", "_About", null, "gtk-about");
			this.aboutAction.ShortLabel = "_About";
			w1.Add (this.aboutAction, null);
			this.openAction = new global::Gtk.Action ("openAction", "_Open", null, "gtk-open");
			this.openAction.ShortLabel = "_Open";
			w1.Add (this.openAction, null);
			this.quitAction = new global::Gtk.Action ("quitAction", "_Quit", null, "gtk-quit");
			this.quitAction.ShortLabel = "_Quit";
			w1.Add (this.quitAction, null);
			this.ViewAction = new global::Gtk.Action ("ViewAction", "_View", null, null);
			this.ViewAction.ShortLabel = "_View";
			w1.Add (this.ViewAction, null);
			this.goForwardAction = new global::Gtk.Action ("goForwardAction", "_Forward", null, "gtk-go-forward");
			this.goForwardAction.ShortLabel = "_Forward";
			w1.Add (this.goForwardAction, "Page_Down");
			this.goBackAction = new global::Gtk.Action ("goBackAction", "_Back", null, "gtk-go-back");
			this.goBackAction.ShortLabel = "_Back";
			w1.Add (this.goBackAction, "Page_Up");
			this.GoToAction = new global::Gtk.Action ("GoToAction", "Go to...", null, null);
			this.GoToAction.ShortLabel = "Go to...";
			w1.Add (this.GoToAction, null);
			this.gotoFirstAction = new global::Gtk.Action ("gotoFirstAction", "_First block", null, "gtk-goto-first");
			this.gotoFirstAction.ShortLabel = "_First block";
			w1.Add (this.gotoFirstAction, "Home");
			this.gotoLastAction = new global::Gtk.Action ("gotoLastAction", "_Last block", null, "gtk-goto-last");
			this.gotoLastAction.ShortLabel = "_Last block";
			w1.Add (this.gotoLastAction, "End");
			this.indexAction = new global::Gtk.Action ("indexAction", "_Position", null, "gtk-index");
			this.indexAction.ShortLabel = "_Position";
			w1.Add (this.indexAction, null);
			this.closeAction = new global::Gtk.Action ("closeAction", "_Close", null, "gtk-close");
			this.closeAction.ShortLabel = "_Close";
			w1.Add (this.closeAction, null);
			this.ViewToolbarAction = new global::Gtk.ToggleAction ("ViewToolbarAction", "View _Toolbar", null, null);
			this.ViewToolbarAction.Active = true;
			this.ViewToolbarAction.ShortLabel = "View _Toolbar";
			w1.Add (this.ViewToolbarAction, null);
			this.positionAction = new global::Gtk.Action ("positionAction", "Go to _position...", null, "gtk-index");
			this.positionAction.ShortLabel = "Go to _position...";
			w1.Add (this.positionAction, "<Control>g");
			this.findAction = new global::Gtk.Action ("findAction", "_Find", null, "gtk-find");
			this.findAction.ShortLabel = "_Find";
			w1.Add (this.findAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "Visor.Ui.MainWindow";
			this.Title = "MainWindow";
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("visor.res.Gafas.png");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Visor.Ui.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString (@"<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='openAction' action='openAction'/><menuitem name='closeAction' action='closeAction'/><menuitem name='quitAction' action='quitAction'/></menu><menu name='ViewAction' action='ViewAction'><menuitem name='ViewToolbarAction' action='ViewToolbarAction'/><menuitem name='goForwardAction' action='goForwardAction'/><menuitem name='goBackAction' action='goBackAction'/><menuitem name='gotoFirstAction' action='gotoFirstAction'/><menuitem name='gotoLastAction' action='gotoLastAction'/><menuitem name='positionAction' action='positionAction'/><menuitem name='findAction' action='findAction'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='aboutAction' action='aboutAction'/></menu></menubar></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.vbox1.Add (this.menubar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString (@"<ui><toolbar name='tbToolbar'><toolitem name='openAction' action='openAction'/><toolitem name='closeAction' action='closeAction'/><separator/><toolitem name='gotoFirstAction' action='gotoFirstAction'/><toolitem name='goBackAction' action='goBackAction'/><toolitem name='goForwardAction' action='goForwardAction'/><toolitem name='gotoLastAction' action='gotoLastAction'/><separator/><toolitem name='positionAction' action='positionAction'/><toolitem name='findAction' action='findAction'/></toolbar></ui>");
			this.tbToolbar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/tbToolbar")));
			this.tbToolbar.Name = "tbToolbar";
			this.tbToolbar.ShowArrow = false;
			this.hbox3.Add (this.tbToolbar);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.tbToolbar]));
			w3.Position = 0;
			this.vbox1.Add (this.hbox3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbPanelGo = new global::Gtk.HBox ();
			this.hbPanelGo.Name = "hbPanelGo";
			this.hbPanelGo.Spacing = 6;
			this.hbPanelGo.BorderWidth = ((uint)(5));
			// Container child hbPanelGo.Gtk.Box+BoxChild
			this.sbFilePosition = new global::Gtk.SpinButton (0D, 100D, 1D);
			this.sbFilePosition.CanFocus = true;
			this.sbFilePosition.Name = "sbFilePosition";
			this.sbFilePosition.Adjustment.PageIncrement = 10D;
			this.sbFilePosition.ClimbRate = 1D;
			this.sbFilePosition.Numeric = true;
			this.hbPanelGo.Add (this.sbFilePosition);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbPanelGo [this.sbFilePosition]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbPanelGo.Gtk.Box+BoxChild
			this.btCloseGoPanel = new global::Gtk.Button ();
			this.btCloseGoPanel.CanFocus = true;
			this.btCloseGoPanel.Name = "btCloseGoPanel";
			this.btCloseGoPanel.UseStock = true;
			this.btCloseGoPanel.UseUnderline = true;
			this.btCloseGoPanel.Label = "gtk-close";
			this.hbPanelGo.Add (this.btCloseGoPanel);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbPanelGo [this.btCloseGoPanel]));
			w6.PackType = ((global::Gtk.PackType)(1));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.vbox1.Add (this.hbPanelGo);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbPanelGo]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbPanelFind = new global::Gtk.HBox ();
			this.hbPanelFind.Name = "hbPanelFind";
			this.hbPanelFind.Spacing = 6;
			this.hbPanelFind.BorderWidth = ((uint)(5));
			// Container child hbPanelFind.Gtk.Box+BoxChild
			this.edFind = new global::Gtk.Entry ();
			this.edFind.CanFocus = true;
			this.edFind.Name = "edFind";
			this.edFind.IsEditable = true;
			this.edFind.InvisibleChar = '•';
			this.hbPanelFind.Add (this.edFind);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbPanelFind [this.edFind]));
			w8.Position = 0;
			// Container child hbPanelFind.Gtk.Box+BoxChild
			this.cbType = global::Gtk.ComboBox.NewText ();
			this.cbType.AppendText ("Txt");
			this.cbType.AppendText ("Hex");
			this.cbType.AppendText ("Dec");
			this.cbType.AppendText ("");
			this.cbType.Name = "cbType";
			this.cbType.Active = 0;
			this.hbPanelFind.Add (this.cbType);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbPanelFind [this.cbType]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbPanelFind.Gtk.Box+BoxChild
			this.btFind = new global::Gtk.Button ();
			this.btFind.CanFocus = true;
			this.btFind.Name = "btFind";
			this.btFind.UseStock = true;
			this.btFind.UseUnderline = true;
			this.btFind.Label = "gtk-find";
			this.hbPanelFind.Add (this.btFind);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbPanelFind [this.btFind]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbPanelFind.Gtk.Box+BoxChild
			this.btCloseFindPanel = new global::Gtk.Button ();
			this.btCloseFindPanel.CanFocus = true;
			this.btCloseFindPanel.Name = "btCloseFindPanel";
			this.btCloseFindPanel.UseStock = true;
			this.btCloseFindPanel.UseUnderline = true;
			this.btCloseFindPanel.Label = "gtk-close";
			this.hbPanelFind.Add (this.btCloseFindPanel);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbPanelFind [this.btCloseFindPanel]));
			w11.Position = 3;
			w11.Expand = false;
			w11.Fill = false;
			this.vbox1.Add (this.hbPanelFind);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbPanelFind]));
			w12.Position = 3;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.frFile1 = new global::Gtk.Frame ();
			this.frFile1.Name = "frFile1";
			this.frFile1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frFile1.Gtk.Container+ContainerChild
			this.GtkAlignment7 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment7.Name = "GtkAlignment7";
			this.GtkAlignment7.LeftPadding = ((uint)(12));
			// Container child GtkAlignment7.Gtk.Container+ContainerChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.nbView = new global::Gtk.Notebook ();
			this.nbView.CanFocus = true;
			this.nbView.Name = "nbView";
			this.nbView.CurrentPage = 0;
			// Container child nbView.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.tvFile = new global::Gtk.TreeView ();
			this.tvFile.CanFocus = true;
			this.tvFile.Name = "tvFile";
			this.GtkScrolledWindow1.Add (this.tvFile);
			this.nbView.Add (this.GtkScrolledWindow1);
			// Notebook tab
			this.lblHexPage = new global::Gtk.Label ();
			this.lblHexPage.Name = "lblHexPage";
			this.lblHexPage.LabelProp = "bin";
			this.nbView.SetTabLabel (this.GtkScrolledWindow1, this.lblHexPage);
			this.lblHexPage.ShowAll ();
			// Container child nbView.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.txtFile = new global::Gtk.TextView ();
			this.txtFile.CanFocus = true;
			this.txtFile.Name = "txtFile";
			this.txtFile.Editable = false;
			this.txtFile.WrapMode = ((global::Gtk.WrapMode)(1));
			this.GtkScrolledWindow.Add (this.txtFile);
			this.nbView.Add (this.GtkScrolledWindow);
			global::Gtk.Notebook.NotebookChild w16 = ((global::Gtk.Notebook.NotebookChild)(this.nbView [this.GtkScrolledWindow]));
			w16.Position = 1;
			// Notebook tab
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = "txt";
			this.nbView.SetTabLabel (this.GtkScrolledWindow, this.label3);
			this.label3.ShowAll ();
			this.hbox2.Add (this.nbView);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.nbView]));
			w17.Position = 0;
			this.GtkAlignment7.Add (this.hbox2);
			this.frFile1.Add (this.GtkAlignment7);
			this.frFrame1Label = new global::Gtk.Label ();
			this.frFrame1Label.Name = "frFrame1Label";
			this.frFrame1Label.LabelProp = "<b>File1</b>";
			this.frFrame1Label.UseMarkup = true;
			this.frFile1.LabelWidget = this.frFrame1Label;
			this.hbox1.Add (this.frFile1);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.frFile1]));
			w20.Position = 0;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w21.Position = 4;
			// Container child vbox1.Gtk.Box+BoxChild
			this.stStatusBar = new global::Gtk.Statusbar ();
			this.stStatusBar.Name = "stStatusBar";
			this.stStatusBar.Spacing = 6;
			// Container child stStatusBar.Gtk.Box+BoxChild
			this.hbIndicators = new global::Gtk.HBox ();
			this.hbIndicators.Name = "hbIndicators";
			this.hbIndicators.Spacing = 6;
			// Container child hbIndicators.Gtk.Box+BoxChild
			this.lblMinPos = new global::Gtk.Label ();
			this.lblMinPos.Name = "lblMinPos";
			this.lblMinPos.LabelProp = "<b>0</b>";
			this.lblMinPos.UseMarkup = true;
			this.hbIndicators.Add (this.lblMinPos);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbIndicators [this.lblMinPos]));
			w22.Position = 0;
			w22.Expand = false;
			w22.Fill = false;
			// Container child hbIndicators.Gtk.Box+BoxChild
			this.scrlSideBar = new global::Gtk.HScrollbar (null);
			this.scrlSideBar.Name = "scrlSideBar";
			this.scrlSideBar.Adjustment.Upper = 100D;
			this.scrlSideBar.Adjustment.PageIncrement = 10D;
			this.scrlSideBar.Adjustment.PageSize = 10D;
			this.scrlSideBar.Adjustment.StepIncrement = 1D;
			this.hbIndicators.Add (this.scrlSideBar);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbIndicators [this.scrlSideBar]));
			w23.Position = 1;
			// Container child hbIndicators.Gtk.Box+BoxChild
			this.lblMaxPos = new global::Gtk.Label ();
			this.lblMaxPos.Name = "lblMaxPos";
			this.lblMaxPos.LabelProp = "<b>0</b>";
			this.lblMaxPos.UseMarkup = true;
			this.hbIndicators.Add (this.lblMaxPos);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbIndicators [this.lblMaxPos]));
			w24.Position = 2;
			w24.Expand = false;
			w24.Fill = false;
			// Container child hbIndicators.Gtk.Box+BoxChild
			this.lblPosition = new global::Gtk.Label ();
			this.lblPosition.Name = "lblPosition";
			this.lblPosition.LabelProp = "label1";
			this.hbIndicators.Add (this.lblPosition);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbIndicators [this.lblPosition]));
			w25.Position = 3;
			w25.Expand = false;
			w25.Fill = false;
			this.stStatusBar.Add (this.hbIndicators);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.stStatusBar [this.hbIndicators]));
			w26.Position = 1;
			this.vbox1.Add (this.stStatusBar);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.stStatusBar]));
			w27.Position = 5;
			w27.Expand = false;
			w27.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 594;
			this.DefaultHeight = 514;
			this.hbPanelGo.Hide ();
			this.hbPanelFind.Hide ();
			this.Hide ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.aboutAction.Activated += new global::System.EventHandler (this.OnAbout);
			this.openAction.Activated += new global::System.EventHandler (this.OnOpen);
			this.quitAction.Activated += new global::System.EventHandler (this.OnQuit);
			this.goForwardAction.Activated += new global::System.EventHandler (this.OnGoForward);
			this.goBackAction.Activated += new global::System.EventHandler (this.OnGoBackward);
			this.gotoFirstAction.Activated += new global::System.EventHandler (this.OnGotoFirst);
			this.gotoLastAction.Activated += new global::System.EventHandler (this.OnGotoLast);
			this.indexAction.Activated += new global::System.EventHandler (this.OnGoto);
			this.closeAction.Activated += new global::System.EventHandler (this.OnClose);
			this.ViewToolbarAction.Activated += new global::System.EventHandler (this.OnViewToolbar);
			this.positionAction.Activated += new global::System.EventHandler (this.OnGoto);
			this.findAction.Activated += new global::System.EventHandler (this.OnFind);
			this.sbFilePosition.ValueChanged += new global::System.EventHandler (this.OnFilePositionChanged);
			this.btCloseGoPanel.Clicked += new global::System.EventHandler (this.OnGoPanelClose);
			this.btFind.Clicked += new global::System.EventHandler (this.OnFindClicked);
			this.btCloseFindPanel.Clicked += new global::System.EventHandler (this.OnFindPanelClose);
			this.scrlSideBar.ValueChanged += new global::System.EventHandler (this.OnSidebarUpdated);
		}
	}
}
